server:
  port: 8084
spring:
   application:
     name: USER-SERVICE
   datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 1234
   jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  instance:
  prefer-ip-address: true
  client:
   fetch-registry: true
  register-with-eureka: true
  service-url:
   defaultZone:http://localhost:9191/eureka
